"""Self-contained, offline evidence report. No remote assets or tracking."""
import html
import json
from pathlib import Path


def render(report, destination):
    esc = lambda v: html.escape(str(v))
    metrics = report["evaluation"]["metrics"]
    cards = [("Evaluation pass rate", f'{metrics["pass_rate"]:.0%}', f'{metrics["case_count"]} scripted cases'),
             ("Schema compliance", f'{metrics["schema_compliance"]:.0%}', 'Validated before delivery'),
             ("Demo accounted cost", f'${report["state"]["accounted_usd"]:.6f}', 'Illustrative rates, no real spend'),
             ("Regression gate", "PASS" if not report["regressions"] else "FAIL", 'Compared with committed baseline')]
    card_html = ''.join(f'<article><label>{esc(a)}</label><strong>{esc(b)}</strong><small>{esc(c)}</small></article>' for a,b,c in cards)
    scenarios = ''
    for scenario in report['scenarios']:
        result = scenario.get('result', {})
        details = ''.join(f'<div class="event"><span>{esc(e["type"])}</span><code>{esc(json.dumps(e["data"], sort_keys=True))}</code></div>' for e in scenario['events'])
        scenarios += f'<details><summary><b>{esc(scenario["title"])}</b><span>{esc(result.get("model", scenario.get("error", "")))}</span></summary><p>{esc(scenario["description"])}</p><blockquote>{esc(result.get("text", scenario.get("error", "")))}</blockquote>{details}</details>'
    rows = ''.join(f'<tr><td>{esc(r["id"])}</td><td>{esc(r["task"])}</td><td><span class="badge">{"PASS" if r["passed"] else "FAIL"}</span></td><td>{r["lexical_f1"]:.2f}</td><td>{r["latency_ms"]:.2f} ms</td><td>${r["cost_usd"]:.6f}</td></tr>' for r in report['evaluation']['cases'])
    page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ModelForge | Run evidence</title><style>
    *{box-sizing:border-box}body{margin:0;background:#f4f5f1;color:#19372d;font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{background:#133d30;color:#fff;padding:40px max(6vw,24px) 48px}.top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ffffff30;padding-bottom:22px}.brand{font-weight:700;font-size:22px;letter-spacing:-1px}.tag{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#c0e5a1}h1{font-size:clamp(30px,5vw,54px);line-height:1.12;letter-spacing:-2px;max-width:760px;margin:36px 0 18px}header p{color:#ccdad2;max-width:660px}main{max-width:1250px;margin:auto;padding:32px 28px}section{margin:35px 0}h2{font-size:23px;letter-spacing:-.5px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}article{background:#fff;border:1px solid #d9dfd6;padding:22px;border-radius:12px}label,small{display:block;color:#62746a}label{font-size:12px}strong{display:block;font-size:32px;letter-spacing:-1px;margin:9px 0}small{font-size:11px}.note{border-left:3px solid #718e42;padding:10px 18px;background:#e9eedf;color:#475c45;font-size:13px}.flow{display:flex;gap:10px;flex-wrap:wrap}.flow span{padding:12px 20px;border:1px solid #cbd5cb;border-radius:6px;background:white}.flow i{font-style:normal;align-self:center;color:#718e42}details{background:white;border:1px solid #d9dfd6;border-radius:9px;margin:10px 0;padding:16px 20px}summary{cursor:pointer;display:flex;justify-content:space-between;gap:16px}summary span{font:12px monospace;color:#617653}blockquote{margin:16px 0;background:#f4f6f0;padding:14px;border-left:3px solid #93ac61}.event{display:grid;grid-template-columns:95px 1fr;gap:12px;border-top:1px solid #eef0ea;padding:9px 0;font-size:12px}.event span{text-transform:uppercase;font-size:10px;font-weight:bold;color:#687f4d}code{white-space:pre-wrap;overflow-wrap:anywhere;color:#4e6255}.table{overflow:auto}table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #d9dfd6;font-size:13px}td,th{text-align:left;padding:14px;border-bottom:1px solid #e5e9e0;white-space:nowrap}th{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#71806c}.badge{color:#315e32;background:#e9f2dc;border-radius:4px;padding:4px 7px;font-size:10px;font-weight:700}footer{font-size:12px;color:#6c7a70;border-top:1px solid #d3dccf;padding-top:22px;margin-top:40px}@media(max-width:800px){.cards{grid-template-columns:repeat(2,1fr)}main{padding:20px 16px}.event{grid-template-columns:1fr}}@media(max-width:440px){.cards{grid-template-columns:1fr}.top{align-items:start;gap:20px}}
    </style><header><div class="top"><div class="brand">◈ ModelForge</div><div class="tag">Gateway / Routing / EvalOps</div></div><h1>Every request has a route.<br>Every route has a reason.</h1><p>A reproducible gateway run with visible decisions, controlled failures, budget accounting, and evaluation evidence.</p><div class="tag">LOCAL DEMO · SCRIPTED PROVIDERS · NO API KEYS</div></header><main><div class="cards">CARDS</div><section class="note">These results exercise real gateway code with deterministic fixtures. Quality scores and prices are illustrative. They do not benchmark live models or establish production performance.</section><section><h2>The request path</h2><div class="flow"><span>Validate</span><i>→</i><span>Rank routes</span><i>→</i><span>Reserve budget</span><i>→</i><span>Stream + recover</span><i>→</i><span>Validate + account</span></div></section><section><h2>Routing in practice</h2><p>Expand each scenario to inspect the actual decision trace.</p>SCENARIOS</section><section><h2>Evaluation ledger</h2><div class="table"><table><thead><tr><th>Case</th><th>Task</th><th>Outcome</th><th>Lexical F1</th><th>Latency</th><th>Accounted cost</th></tr></thead><tbody>ROWS</tbody></table></div><p><small>Lexical F1 is an overlap proxy. A live LLM judge is optional and was not run in this demo.</small></p></section><footer>ModelForge v0.1 · Reference implementation · Inspect report.json for the full machine-readable evidence.</footer></main></html>'''
    Path(destination).write_text(page.replace('CARDS',card_html).replace('SCENARIOS',scenarios).replace('ROWS',rows))
